#############################################################################
# Makefile for building: UDPSocket
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  UDPSocket.pro
# Template: app
# Command: /shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/qmake -o Makefile UDPSocket.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt -I/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtGui -I/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtCore -I. -I/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++
QMAKE         = /shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/qmake -install qinstall
QINSTALL_PROGRAM = /shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = UDPSocket1.0.0
DISTDIR = /business/Projects/Application_Ver2/UDPSocket/.tmp/UDPSocket1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/shared/Applications/anaconda3/[shared/Applications/anaconda3]/lib
LIBS          = $(SUBLIBS) -L/shared/Applications/anaconda3/[shared/Applications/anaconda3]/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = client.cpp \
		clientcpnet.cpp \
		clientinterface.cpp \
		commandlineinterface.cpp \
		commons.cpp \
		getfilewindow.cpp \
		loginview.cpp \
		loginwidget.cpp \
		main.cpp \
		mainWindow.cpp \
		md5.cpp \
		messageprotocol.cpp \
		server.cpp \
		servercpnet.cpp \
		serverinterface.cpp \
		syncinput.cpp \
		syncoutput.cpp \
		user.cpp \
		libcpnet-dev/src/cpnet-network.c \
		libcpnet-dev/test/common.c \
		libcpnet-dev/test/tcp-client.c \
		libcpnet-dev/test/tcp-server.c \
		libcpnet-dev/test/test-win.c \
		libcpnet-dev/test/udp-client.c \
		libcpnet-dev/test/udp-server.c moc_getfilewindow.cpp \
		moc_loginview.cpp \
		moc_mainwinow.cpp
OBJECTS       = client.o \
		clientcpnet.o \
		clientinterface.o \
		commandlineinterface.o \
		commons.o \
		getfilewindow.o \
		loginview.o \
		loginwidget.o \
		main.o \
		mainWindow.o \
		md5.o \
		messageprotocol.o \
		server.o \
		servercpnet.o \
		serverinterface.o \
		syncinput.o \
		syncoutput.o \
		user.o \
		cpnet-network.o \
		common.o \
		tcp-client.o \
		tcp-server.o \
		test-win.o \
		udp-client.o \
		udp-server.o \
		moc_getfilewindow.o \
		moc_loginview.o \
		moc_mainwinow.o
DIST          = /shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/spec_pre.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/unix.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/linux.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/sanitize.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/gcc-base.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/gcc-base-unix.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/g++-base.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/g++-unix.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/qconfig.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3danimation.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3danimation_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dcore.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dcore_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dextras.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dextras_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dinput.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dinput_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dlogic.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquick.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquick_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickextras.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickinput.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickrender.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3drender.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3drender_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bluetooth.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_charts.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_charts_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_concurrent.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_concurrent_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_core.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_core_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_datavisualization.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_dbus.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_dbus_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designer.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designer_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_egl_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_fb_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gamepad.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gamepad_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_glx_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gui.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gui_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_help.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_help_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_input_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_location.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_location_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimedia.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimedia_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_network.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_network_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_networkauth.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_networkauth_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_nfc.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_nfc_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_opengl.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_opengl_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_openglextensions.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_positioning.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_positioning_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_printsupport.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_printsupport_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_purchasing.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_purchasing_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qml.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qml_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmltest.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmltest_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quick.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quick_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickwidgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_remoteobjects.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_repparser.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_repparser_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_script.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_script_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scripttools.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scripttools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scxml.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scxml_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sensors.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sensors_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialbus.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialbus_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialport.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialport_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_service_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sql.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sql_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_svg.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_svg_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_testlib.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_testlib_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_texttospeech.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_theme_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uiplugin.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uitools.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uitools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webchannel.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webchannel_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webengine.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webengine_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecore.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_websockets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_websockets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webview.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webview_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_widgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_widgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_x11extras.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_x11extras_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xml.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xml_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt_functions.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt_config.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++/qmake.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/spec_post.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/exclusive_builds.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/toolchain.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/default_pre.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/resolve_config.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/default_post.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/warn_on.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/resources.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/moc.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/unix/opengl.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/unix/thread.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qmake_use.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/file_copies.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/testcase_targets.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/exceptions.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/yacc.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/lex.prf \
		UDPSocket.pro client.h \
		clientcpnet.h \
		clientinterface.h \
		commandlineinterface.h \
		commons.h \
		getfilewindow.h \
		loginview.h \
		loginwidget.h \
		mainwindow.h \
		mainwinow.h \
		md5.h \
		messageprotocol.h \
		server.h \
		servercpnet.h \
		serverinterface.h \
		syncinput.h \
		syncoutput.h \
		user.h \
		libcpnet-dev/config.h \
		libcpnet-dev/src/cpnet-export.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/test/common-win.h \
		libcpnet-dev/test/common.h \
		libcpnet-dev/win32/resource.h \
		libcpnet-dev/output/include/cpnet/cpnet-export.h \
		libcpnet-dev/output/include/cpnet/cpnet-network.h client.cpp \
		clientcpnet.cpp \
		clientinterface.cpp \
		commandlineinterface.cpp \
		commons.cpp \
		getfilewindow.cpp \
		loginview.cpp \
		loginwidget.cpp \
		main.cpp \
		mainWindow.cpp \
		md5.cpp \
		messageprotocol.cpp \
		server.cpp \
		servercpnet.cpp \
		serverinterface.cpp \
		syncinput.cpp \
		syncoutput.cpp \
		user.cpp \
		libcpnet-dev/src/cpnet-network.c \
		libcpnet-dev/test/common.c \
		libcpnet-dev/test/tcp-client.c \
		libcpnet-dev/test/tcp-server.c \
		libcpnet-dev/test/test-win.c \
		libcpnet-dev/test/udp-client.c \
		libcpnet-dev/test/udp-server.c
QMAKE_TARGET  = UDPSocket
DESTDIR       = 
TARGET        = UDPSocket


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: UDPSocket.pro /shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++/qmake.conf /shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/spec_pre.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/unix.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/linux.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/sanitize.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/gcc-base.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/gcc-base-unix.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/g++-base.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/g++-unix.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/qconfig.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3danimation.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3danimation_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dcore.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dcore_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dextras.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dextras_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dinput.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dinput_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dlogic.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquick.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquick_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickextras.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickinput.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickrender.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3drender.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3drender_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bluetooth.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_charts.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_charts_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_concurrent.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_concurrent_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_core.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_core_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_datavisualization.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_dbus.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_dbus_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designer.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designer_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_egl_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_fb_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gamepad.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gamepad_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_glx_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gui.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gui_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_help.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_help_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_input_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_location.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_location_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimedia.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimedia_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_network.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_network_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_networkauth.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_networkauth_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_nfc.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_nfc_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_opengl.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_opengl_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_openglextensions.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_positioning.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_positioning_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_printsupport.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_printsupport_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_purchasing.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_purchasing_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qml.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qml_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmltest.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmltest_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quick.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quick_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickwidgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_remoteobjects.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_repparser.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_repparser_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_script.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_script_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scripttools.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scripttools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scxml.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scxml_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sensors.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sensors_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialbus.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialbus_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialport.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialport_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_service_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sql.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sql_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_svg.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_svg_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_testlib.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_testlib_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_texttospeech.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_theme_support_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uiplugin.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uitools.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uitools_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webchannel.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webchannel_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webengine.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webengine_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecore.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_websockets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_websockets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webview.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webview_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_widgets.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_widgets_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_x11extras.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_x11extras_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xml.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xml_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt_functions.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt_config.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++/qmake.conf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/spec_post.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/exclusive_builds.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/toolchain.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/default_pre.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/resolve_config.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/default_post.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/warn_on.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/resources.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/moc.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/unix/opengl.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/unix/thread.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qmake_use.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/file_copies.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/testcase_targets.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/exceptions.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/yacc.prf \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/lex.prf \
		UDPSocket.pro \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/lib/libQt5Gui.prl \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/lib/libQt5Core.prl
	$(QMAKE) -o Makefile UDPSocket.pro
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/spec_pre.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/unix.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/linux.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/sanitize.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/gcc-base.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/gcc-base-unix.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/g++-base.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/common/g++-unix.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/qconfig.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3danimation.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3danimation_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dcore.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dcore_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dextras.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dextras_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dinput.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dinput_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dlogic.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dlogic_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquick.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquick_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickanimation.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickextras.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickinput.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickrender.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3drender.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_3drender_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bluetooth.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bluetooth_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_bootstrap_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_charts.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_charts_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_concurrent.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_concurrent_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_core.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_core_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_datavisualization.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_datavisualization_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_dbus.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_dbus_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designer.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designer_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_designercomponents_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_egl_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_fb_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gamepad.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gamepad_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_glx_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gui.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_gui_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_help.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_help_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_input_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_location.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_location_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimedia.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimedia_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimediawidgets.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_network.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_network_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_networkauth.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_networkauth_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_nfc.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_nfc_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_opengl.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_opengl_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_openglextensions.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_openglextensions_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_positioning.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_positioning_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_printsupport.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_printsupport_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_purchasing.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_purchasing_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qml.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qml_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmldebug_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmltest.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qmltest_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quick.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quick_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickcontrols2.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickparticles_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickwidgets.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_remoteobjects.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_repparser.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_repparser_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_script.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_script_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scripttools.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scripttools_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scxml.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_scxml_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sensors.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sensors_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialbus.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialbus_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialport.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_serialport_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_service_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sql.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_sql_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_svg.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_svg_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_testlib.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_testlib_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_texttospeech.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_texttospeech_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_theme_support_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uiplugin.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uitools.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_uitools_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webchannel.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webchannel_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webengine.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webengine_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecore.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecore_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginewidgets.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_websockets.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_websockets_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webview.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_webview_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_widgets.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_widgets_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_x11extras.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_x11extras_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xml.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xml_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xmlpatterns.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt_functions.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt_config.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++/qmake.conf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/spec_post.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/exclusive_builds.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/toolchain.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/default_pre.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/resolve_config.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/default_post.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/warn_on.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qt.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/resources.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/moc.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/unix/opengl.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/unix/thread.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/qmake_use.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/file_copies.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/testcase_targets.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/exceptions.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/yacc.prf:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/lex.prf:
UDPSocket.pro:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/lib/libQt5Gui.prl:
/shared/Applications/anaconda3/[shared/Applications/anaconda3]/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile UDPSocket.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents client.h clientcpnet.h clientinterface.h commandlineinterface.h commons.h getfilewindow.h loginview.h loginwidget.h mainwindow.h mainwinow.h md5.h messageprotocol.h server.h servercpnet.h serverinterface.h syncinput.h syncoutput.h user.h libcpnet-dev/config.h libcpnet-dev/src/cpnet-export.h libcpnet-dev/src/cpnet-network.h libcpnet-dev/test/common-win.h libcpnet-dev/test/common.h libcpnet-dev/win32/resource.h libcpnet-dev/output/include/cpnet/cpnet-export.h libcpnet-dev/output/include/cpnet/cpnet-network.h $(DISTDIR)/
	$(COPY_FILE) --parents client.cpp clientcpnet.cpp clientinterface.cpp commandlineinterface.cpp commons.cpp getfilewindow.cpp loginview.cpp loginwidget.cpp main.cpp mainWindow.cpp md5.cpp messageprotocol.cpp server.cpp servercpnet.cpp serverinterface.cpp syncinput.cpp syncoutput.cpp user.cpp libcpnet-dev/src/cpnet-network.c libcpnet-dev/test/common.c libcpnet-dev/test/tcp-client.c libcpnet-dev/test/tcp-server.c libcpnet-dev/test/test-win.c libcpnet-dev/test/udp-client.c libcpnet-dev/test/udp-server.c $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_getfilewindow.cpp moc_loginview.cpp moc_mainwinow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_getfilewindow.cpp moc_loginview.cpp moc_mainwinow.cpp
moc_getfilewindow.cpp: client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		getfilewindow.h \
		moc_predefs.h \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/moc
	'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/moc' $(DEFINES) --include ./moc_predefs.h -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++' -I/business/Projects/Application_Ver2/UDPSocket -I/business/Projects/Application_Ver2/UDPSocket -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt' -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtGui' -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtCore' -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include getfilewindow.h -o moc_getfilewindow.cpp

moc_loginview.cpp: client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		loginview.h \
		moc_predefs.h \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/moc
	'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/moc' $(DEFINES) --include ./moc_predefs.h -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++' -I/business/Projects/Application_Ver2/UDPSocket -I/business/Projects/Application_Ver2/UDPSocket -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt' -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtGui' -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtCore' -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include loginview.h -o moc_loginview.cpp

moc_mainwinow.cpp: loginview.h \
		client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		getfilewindow.h \
		mainwinow.h \
		moc_predefs.h \
		/shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/moc
	'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/bin/moc' $(DEFINES) --include ./moc_predefs.h -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/mkspecs/linux-g++' -I/business/Projects/Application_Ver2/UDPSocket -I/business/Projects/Application_Ver2/UDPSocket -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt' -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtGui' -I'/shared/Applications/anaconda3/[shared/Applications/anaconda3]/include/qt/QtCore' -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwinow.h -o moc_mainwinow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

client.o: client.cpp client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

clientcpnet.o: clientcpnet.cpp clientcpnet.h \
		clientinterface.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		commons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientcpnet.o clientcpnet.cpp

clientinterface.o: clientinterface.cpp clientinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientinterface.o clientinterface.cpp

commandlineinterface.o: commandlineinterface.cpp commandlineinterface.h \
		client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandlineinterface.o commandlineinterface.cpp

commons.o: commons.cpp commons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commons.o commons.cpp

getfilewindow.o: getfilewindow.cpp getfilewindow.h \
		client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getfilewindow.o getfilewindow.cpp

loginview.o: loginview.cpp loginview.h \
		client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginview.o loginview.cpp

loginwidget.o: loginwidget.cpp loginwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwidget.o loginwidget.cpp

main.o: main.cpp server.h \
		serverinterface.h \
		servercpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		user.h \
		syncoutput.h \
		messageprotocol.h \
		client.h \
		clientinterface.h \
		clientcpnet.h \
		syncinput.h \
		commons.h \
		commandlineinterface.h \
		mainwinow.h \
		loginview.h \
		getfilewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cpp mainwinow.h \
		loginview.h \
		client.h \
		clientinterface.h \
		clientcpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		syncoutput.h \
		syncinput.h \
		messageprotocol.h \
		getfilewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

md5.o: md5.cpp md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o md5.o md5.cpp

messageprotocol.o: messageprotocol.cpp messageprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messageprotocol.o messageprotocol.cpp

server.o: server.cpp server.h \
		serverinterface.h \
		servercpnet.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		user.h \
		syncoutput.h \
		messageprotocol.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

servercpnet.o: servercpnet.cpp servercpnet.h \
		serverinterface.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		commons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servercpnet.o servercpnet.cpp

serverinterface.o: serverinterface.cpp serverinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverinterface.o serverinterface.cpp

syncinput.o: syncinput.cpp syncinput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syncinput.o syncinput.cpp

syncoutput.o: syncoutput.cpp syncoutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syncoutput.o syncoutput.cpp

user.o: user.cpp user.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

cpnet-network.o: libcpnet-dev/src/cpnet-network.c libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cpnet-network.o libcpnet-dev/src/cpnet-network.c

common.o: libcpnet-dev/test/common.c libcpnet-dev/test/common.h \
		libcpnet-dev/test/common-win.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o common.o libcpnet-dev/test/common.c

tcp-client.o: libcpnet-dev/test/tcp-client.c libcpnet-dev/test/common.h \
		libcpnet-dev/test/common-win.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tcp-client.o libcpnet-dev/test/tcp-client.c

tcp-server.o: libcpnet-dev/test/tcp-server.c libcpnet-dev/test/common.h \
		libcpnet-dev/test/common-win.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tcp-server.o libcpnet-dev/test/tcp-server.c

test-win.o: libcpnet-dev/test/test-win.c libcpnet-dev/test/common-win.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o test-win.o libcpnet-dev/test/test-win.c

udp-client.o: libcpnet-dev/test/udp-client.c libcpnet-dev/test/common.h \
		libcpnet-dev/test/common-win.h \
		libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o udp-client.o libcpnet-dev/test/udp-client.c

udp-server.o: libcpnet-dev/test/udp-server.c libcpnet-dev/src/cpnet-network.h \
		libcpnet-dev/src/cpnet-export.h \
		libcpnet-dev/test/common.h \
		libcpnet-dev/test/common-win.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o udp-server.o libcpnet-dev/test/udp-server.c

moc_getfilewindow.o: moc_getfilewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_getfilewindow.o moc_getfilewindow.cpp

moc_loginview.o: moc_loginview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginview.o moc_loginview.cpp

moc_mainwinow.o: moc_mainwinow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwinow.o moc_mainwinow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

